/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Model#getRegressions <em>Regressions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Regressions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Regressions</em>' containment reference.
   * @see #setRegressions(Regression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getModel_Regressions()
   * @model containment="true"
   * @generated
   */
  Regression getRegressions();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Model#getRegressions <em>Regressions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Regressions</em>' containment reference.
   * @see #getRegressions()
   * @generated
   */
  void setRegressions(Regression value);

} // Model
