/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Regressions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__REGRESSIONS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RegressionImpl <em>Regression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RegressionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRegression()
   * @generated
   */
  int REGRESSION = 1;

  /**
   * The feature id for the '<em><b>Fichier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGRESSION__FICHIER = 0;

  /**
   * The feature id for the '<em><b>Delimiteur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGRESSION__DELIMITEUR = 1;

  /**
   * The feature id for the '<em><b>Algorithme</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGRESSION__ALGORITHME = 2;

  /**
   * The feature id for the '<em><b>Predire</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGRESSION__PREDIRE = 3;

  /**
   * The number of structural features of the '<em>Regression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGRESSION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FichierImpl <em>Fichier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FichierImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFichier()
   * @generated
   */
  int FICHIER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FICHIER__NAME = 0;

  /**
   * The number of structural features of the '<em>Fichier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FICHIER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DelimiteurImpl <em>Delimiteur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DelimiteurImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDelimiteur()
   * @generated
   */
  int DELIMITEUR = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELIMITEUR__NAME = 0;

  /**
   * The number of structural features of the '<em>Delimiteur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELIMITEUR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.PredireImpl <em>Predire</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.PredireImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPredire()
   * @generated
   */
  int PREDIRE = 4;

  /**
   * The feature id for the '<em><b>Pourcentage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDIRE__POURCENTAGE = 0;

  /**
   * The number of structural features of the '<em>Predire</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDIRE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.Algorithme <em>Algorithme</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.Algorithme
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAlgorithme()
   * @generated
   */
  int ALGORITHME = 5;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Model#getRegressions <em>Regressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Regressions</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getRegressions()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Regressions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Regression <em>Regression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Regression</em>'.
   * @see org.xtext.example.mydsl.myDsl.Regression
   * @generated
   */
  EClass getRegression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Regression#getFichier <em>Fichier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fichier</em>'.
   * @see org.xtext.example.mydsl.myDsl.Regression#getFichier()
   * @see #getRegression()
   * @generated
   */
  EReference getRegression_Fichier();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Regression#getDelimiteur <em>Delimiteur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Delimiteur</em>'.
   * @see org.xtext.example.mydsl.myDsl.Regression#getDelimiteur()
   * @see #getRegression()
   * @generated
   */
  EReference getRegression_Delimiteur();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Regression#getAlgorithme <em>Algorithme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Algorithme</em>'.
   * @see org.xtext.example.mydsl.myDsl.Regression#getAlgorithme()
   * @see #getRegression()
   * @generated
   */
  EAttribute getRegression_Algorithme();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Regression#getPredire <em>Predire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predire</em>'.
   * @see org.xtext.example.mydsl.myDsl.Regression#getPredire()
   * @see #getRegression()
   * @generated
   */
  EReference getRegression_Predire();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Fichier <em>Fichier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fichier</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fichier
   * @generated
   */
  EClass getFichier();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Fichier#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fichier#getName()
   * @see #getFichier()
   * @generated
   */
  EAttribute getFichier_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Delimiteur <em>Delimiteur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delimiteur</em>'.
   * @see org.xtext.example.mydsl.myDsl.Delimiteur
   * @generated
   */
  EClass getDelimiteur();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Delimiteur#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Delimiteur#getName()
   * @see #getDelimiteur()
   * @generated
   */
  EAttribute getDelimiteur_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Predire <em>Predire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predire</em>'.
   * @see org.xtext.example.mydsl.myDsl.Predire
   * @generated
   */
  EClass getPredire();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Predire#getPourcentage <em>Pourcentage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pourcentage</em>'.
   * @see org.xtext.example.mydsl.myDsl.Predire#getPourcentage()
   * @see #getPredire()
   * @generated
   */
  EAttribute getPredire_Pourcentage();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.Algorithme <em>Algorithme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Algorithme</em>'.
   * @see org.xtext.example.mydsl.myDsl.Algorithme
   * @generated
   */
  EEnum getAlgorithme();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Regressions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__REGRESSIONS = eINSTANCE.getModel_Regressions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RegressionImpl <em>Regression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RegressionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRegression()
     * @generated
     */
    EClass REGRESSION = eINSTANCE.getRegression();

    /**
     * The meta object literal for the '<em><b>Fichier</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGRESSION__FICHIER = eINSTANCE.getRegression_Fichier();

    /**
     * The meta object literal for the '<em><b>Delimiteur</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGRESSION__DELIMITEUR = eINSTANCE.getRegression_Delimiteur();

    /**
     * The meta object literal for the '<em><b>Algorithme</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGRESSION__ALGORITHME = eINSTANCE.getRegression_Algorithme();

    /**
     * The meta object literal for the '<em><b>Predire</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGRESSION__PREDIRE = eINSTANCE.getRegression_Predire();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FichierImpl <em>Fichier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FichierImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFichier()
     * @generated
     */
    EClass FICHIER = eINSTANCE.getFichier();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FICHIER__NAME = eINSTANCE.getFichier_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DelimiteurImpl <em>Delimiteur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DelimiteurImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDelimiteur()
     * @generated
     */
    EClass DELIMITEUR = eINSTANCE.getDelimiteur();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DELIMITEUR__NAME = eINSTANCE.getDelimiteur_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.PredireImpl <em>Predire</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.PredireImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPredire()
     * @generated
     */
    EClass PREDIRE = eINSTANCE.getPredire();

    /**
     * The meta object literal for the '<em><b>Pourcentage</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDIRE__POURCENTAGE = eINSTANCE.getPredire_Pourcentage();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.Algorithme <em>Algorithme</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.Algorithme
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAlgorithme()
     * @generated
     */
    EEnum ALGORITHME = eINSTANCE.getAlgorithme();

  }

} //MyDslPackage
