/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predire</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Predire#getPourcentage <em>Pourcentage</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPredire()
 * @model
 * @generated
 */
public interface Predire extends EObject
{
  /**
   * Returns the value of the '<em><b>Pourcentage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pourcentage</em>' attribute.
   * @see #setPourcentage(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPredire_Pourcentage()
   * @model
   * @generated
   */
  int getPourcentage();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Predire#getPourcentage <em>Pourcentage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pourcentage</em>' attribute.
   * @see #getPourcentage()
   * @generated
   */
  void setPourcentage(int value);

} // Predire
