/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Regression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Regression#getFichier <em>Fichier</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Regression#getDelimiteur <em>Delimiteur</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Regression#getAlgorithme <em>Algorithme</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Regression#getPredire <em>Predire</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRegression()
 * @model
 * @generated
 */
public interface Regression extends EObject
{
  /**
   * Returns the value of the '<em><b>Fichier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fichier</em>' containment reference.
   * @see #setFichier(Fichier)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRegression_Fichier()
   * @model containment="true"
   * @generated
   */
  Fichier getFichier();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Regression#getFichier <em>Fichier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fichier</em>' containment reference.
   * @see #getFichier()
   * @generated
   */
  void setFichier(Fichier value);

  /**
   * Returns the value of the '<em><b>Delimiteur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delimiteur</em>' containment reference.
   * @see #setDelimiteur(Delimiteur)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRegression_Delimiteur()
   * @model containment="true"
   * @generated
   */
  Delimiteur getDelimiteur();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Regression#getDelimiteur <em>Delimiteur</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delimiteur</em>' containment reference.
   * @see #getDelimiteur()
   * @generated
   */
  void setDelimiteur(Delimiteur value);

  /**
   * Returns the value of the '<em><b>Algorithme</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.Algorithme}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algorithme</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Algorithme
   * @see #setAlgorithme(Algorithme)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRegression_Algorithme()
   * @model
   * @generated
   */
  Algorithme getAlgorithme();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Regression#getAlgorithme <em>Algorithme</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Algorithme</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Algorithme
   * @see #getAlgorithme()
   * @generated
   */
  void setAlgorithme(Algorithme value);

  /**
   * Returns the value of the '<em><b>Predire</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predire</em>' containment reference.
   * @see #setPredire(Predire)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRegression_Predire()
   * @model containment="true"
   * @generated
   */
  Predire getPredire();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Regression#getPredire <em>Predire</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predire</em>' containment reference.
   * @see #getPredire()
   * @generated
   */
  void setPredire(Predire value);

} // Regression
